### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by mat304** [cdesjardins/cppssh#1]
I am having some trouble getting ne7ssh to ssh to a Tandberg video conferencing box so I thought that I'd try cppsh out. However, I am not sure what dependant packages are required for the build. In particular CMakeLists.txt wants CDLogger & when I try to build it can't find QueuePtr/ThreadSafeQueue.h. Any ideas would be appreciated.

Cheers, John

**Comment by cdesjardins** [comment]
Indeed, the readme needs to be updated big time, I typically use repo to get all the dependent projects. Give me some time and I will try to update the readme before I head to bed tonight.
Thanks,
    Chris D.

**Comment by cdesjardins** [comment]
Try to see if the instructions work for you now, I only have access to linux right now, so I didn't bother with more details on windows, but hopefully this will get you going.

**Comment by mat304** [comment]
Thanks!

I'll let you know how it goes.

Cheers, John
