### ISSUE TITLE
CBC mode problem

### ISSUE THREAD

**Issue by tamara-utyugova** [cdesjardins/cppssh#2]
Hi. I'm trying to implement SSH protocol with your library. And I try use 3des algo in cbc mode.

I create encryption as follows:

`_encrypt.reset(new Pipe(encryptFilter = new CBC_Encryption(cipher->clone(), new Null_Padding, c2s_key, c2s_iv)));`
I create decryption as follows:

`_decrypt.reset(new Pipe(decryptFilter = new CBC_Decryption(cipher->clone(), new Null_Padding, s2c_key, s2c_iv))); 
`
I try decrypt as follows:

```
bool crypto::decryptPacket(Botan::SecureVector<Botan::byte> &decrypted, Botan::SecureVector<Botan::byte> &packet, uint32_t len)
{
    uint32_t pLen = packet.size();

    if (pLen % _decryptBlock != 0)
    {
        len = pLen + (pLen % _decryptBlock);
    }

    for (uint32_t pktIndex = 0; pktIndex < len; pktIndex += _decryptBlock)
    {
            Botan::SecureVector<Botan::byte> e(packet.begin() + pktIndex, packet.size() + pktIndex + _decryptBlock);
            _decrypt->process_msg(e, _decryptBlock);

            decrypted += _decrypt->read_all(_decrypt->message_count() - 1);
    }

    return true;
}

```

I try encrypt as follows:

```
bool crypto::encryptPacket(Botan::SecureVector<Botan::byte> &crypted, Botan::SecureVector<Botan::byte> &hmac, Botan::SecureVector<Botan::byte> &packet, uint32_t seq)
{
    SecureVector<Botan::byte> macStr;
    uint32_t nSeq = (uint32_t)htonl(seq);

    _encrypt->start_msg();
    _encrypt->write(packet.begin(), packet.size());
    _encrypt->end_msg();

    crypted = _encrypt->read_all(_encrypt->message_count() - 1);

    if (_hmacOut)
    {
        macStr = SecureVector<Botan::byte>((Botan::byte*)&nSeq, 4);
        macStr += packet;
        hmac = _hmacOut->process(macStr);
    }

    return true;
}
```

As a result, encrypted packets normally, but when i tried decrypt the second packet and next packages first block decrypted incorrectly. What is the problem?

**Comment by cdesjardins** [comment]
Sorry for the delayed response, I have been in foreign lands for the last month. I am a bit confused by your question. First you say:

> I'm trying to implement SSH protocol with your library.

Then you give code snippets that do not call my library. If you want to use my library to implement some ssh client then you would call Cppssh::connect() followed by Cppssh::read()/Cppssh::write(), and then Cppssh::close(). You can find the full API at: https://github.com/cdesjardins/cppssh/blob/master/include/cppssh.h
it should be pretty easy to use, there is even an example at:
https://github.com/cdesjardins/cppssh/blob/master/examples/cppsshexample.cpp

Let me know if this helps.
