### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by alienzj** [cdesjardins/cppssh#3]
`-- The CXX compiler identification is GNU 7.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:5 (include):
  include could not find load file:

    compilerflags

CMake Error at CMakeLists.txt:11 (MESSAGE):
  Need to run the makebotan.py script, could not find Botan includes

-- Configuring incomplete, errors occurred!
See also "/home/zhujie/projects/aur/temp/cppssh/build/CMakeFiles/CMakeOutput.log".`

OS: archlinux
GCC: gcc 7.2.0
Botan: botan 2.3.0-1
Cmake: cmake 3.9.4

Thanks very much!

**Comment by cdesjardins** [comment]
I am not sure if I understand this issue, or if you figured it out, but you need to download the other repos for this to compile. You do that with:

repo init -u https://github.com/cdesjardins/cppsshManifest.git 
repo sync
cd build
[./]makebotan.py
[./]build.py --CDLogger --cppssh

As far as I know 80% of the time that works everytime.
